---
- hosts: nodes
  tasks:
  - name: Start Service Spooler
    win_service:
      name: spooler
      state: started 
  
  - name: Execute command in Windows
    win_shell: dir
    args:
        executable: cmd
    register: out

  - debug: var=out.stdout_lines
